# This file is to implement the linearized CCD correction based on the paper by Boguslawski & Ayers (2015)

# Goal: create an implementation for the AP1roG wavefunction that can be generalized to other wavefunctions

### Step 1 ###
# create a basic class for the LCCD correction with the constructor __init__ 

### Step 2 ###
#  generate pool of excitation operators (for AP1roG, this is the E_ai E_bi that corresponds to the parameter t_ij^ab)
# we can store the parameters t_ij^ab as numpy arrays, similarly to how wavefunctions store the wavefunction parameters. 
# We will need a map between the index of a parameter and the corresponding exop. The CC wavefunction does something similar, where self.exops is a dictionary (keys are the excitation operator and value is the parameter index)  (see get_ind and get_exop from BaseCC in fanpy/cc/base.py, and self.exops)

### Step 3 ###
# calculate_b
# calculate the B_mu matrix elements
# for this, we have to call integrate_sd_wfn() of the passed hamiltonian. This returns the element <SD| H | wfn >. Here SD corresponds to the <\mu| excited state determinants generated by the excitation operators 

### Step 4 ###
# calculate_a
# calculate the A_mu_nu elements
# here, we should first simplify the equation (6) in the overleaf document and break it down into chunks. 

### Step 5 ## 
# solve system of linear equations
# this can be a method or something we leave up for the user. Not sure yet if it is best to let the user solve it or just do it in the class. 

### Step 6 ### 
# compute correction
# this should be what the user calls when calculating corrections. 
# It should compute the energy correction as per eq. (7) of the overleaf document

import numpy as np
import scipy as sc

from fanpy.wfn.geminal.ap1rog import AP1roG
from fanpy.tools import slater

class LCCD:
    """
    Attributes:
    wfn : AP1roG
    ham : BaseHamiltonian or ??
    ref_sd : int
        Reference SD from AP1roG
    nspatial : int
    nspin : int
    exops : dict
    nparams : int
    params : np.ndarray with amplitudes

    Methods:
    __init__(self, wfn, ham)
    generate_exops(self)


    """
 


    def __init__(self, wfn, ham, pspace):
        # check if wfn is AP1roG --> currently, we are only implementing the correction for this

        # save wfn and ham as properties
        # self.wfn = wfn
        # self.ham = ham

        # generate pool of double excitation operators 
        
        if not isinstance(wfn, AP1roG):
            raise TypeError("Current LCCD implementation only supports AP1roG.")

        self.wfn = wfn
        self.ham = ham
        self.pspace = pspace

        self.ref_sd = wfn.ref_sd
        self.nspatial = wfn.nspatial
        self.nspin = wfn.nspin


        self.generate_exops()
    

    def generate_exops(self):
        # Get occupied and virtual orbital indices from reference SD
        total_occ = slater.total_occ(self.ref_sd)
        occ_indices = slater.occ_indices(self.ref_sd)
        vir_indices = slater.vir_indices(self.ref_sd, self.nspin)
        alpha_indices, _ = slater.split_spin(self.ref_sd, self.nspatial)
        occ_alpha_indices = slater.occ_indices(alpha_indices)
        vir_alpha_indices = slater.vir_indices(alpha_indices, self.nspatial)
        
        dict_exops_ind = {}
        param_ind = 0
        for i_ind, i in enumerate(occ_alpha_indices):
            for j in occ_alpha_indices[i_ind + 1:]:
                for a_ind, a in enumerate(vir_alpha_indices):
                    for b in vir_alpha_indices[a_ind + 1:]:

                        #if self._is_pair_excitation(i, j, a, b):
                        #    continue
                        
                        # Store excitation operator: (i,j,a,b) -> parameter index
                        dict_exops_ind[(i, j, a, b)] = param_ind
                        param_ind += 1 
        
        self.dict_exops_ind = dict_exops_ind
        self.dict_ind_exops = {i: exops for exops,i in dict_exops_ind.items()}
         
        # Initialize cluster amplitude parameters
        self.nparams = len(self.dict_exops_ind)
        self.amplitudes = np.zeros(self.nparams)


    def _is_pair_excitation(self, i, j, a ,b):
        if j == i + self.nspatial and b == a + self.nspatial:
            return True
        if i == j + self.nspatial and a == b + self.nspatial:
            return True
        return False


    def _generate_sub_exops(self, mu):
        i, j, a, b = mu
        sub_exops = ((i,j,a,b), (i,j+self.nspatial,a,b+self.nspatial), (i+self.nspatial,j,a+self.nspatial,b), (i+self.spatial,j+self.spatial,a+self.spatial,b+self.spatial))
        return sub_exops


    def calculate_b(self):
        b = np.zeros((self.nparams))
        for ind_mu, mu in self.dict_ind_exops.items():
            b_mu = 0.0
            for sub_mu_exop in self._generate_sub_exops(mu):
                sub_exc_refsd = slater.excite(self.ref_sd, sub_mu_exop)
                b_mu += self.ham.integrate_sd_wfn(sub_exc_refsd, self.wfn)
            b[ind_mu] = b_mu
        self.b_vector = b


    def calculate_a(self):
        a = np.zeros((self.nparams, self.nparams))
        const = self.ham.integrate_sd_wfn(self.ref_sd, self.wfn)

        for ind_mu, mu in self.dict_ind_exops.items():

            for ind_nu, nu in self.dict_ind_exops.items():

                for m in self.pspace:
                    a_mu_nu = 0.0
                    for sub_mu_exop in self._generate_sub_exops(mu):
                        sub_exc_mu_refsd = slater.excite(self.ref_sd, sub_mu_exop)
                        for sub_nu_exop in self._generate_sub_exops(nu):
                            sub_exc_nu_m = slater.excite(m, sub_nu_exop)
                            a_mu_nu += self.ham.integrate_sd_sd(sub_exc_mu_refsd, sub_exc_nu_m)
                    a_mu_nu *= self.wfn.get_overlap(m)

                if nu == mu:
                    a_mu_nu -= const
                
                a[ind_mu, ind_nu] = a_mu_nu

        self.a_matrix = a


    def compute_correction(self):
        amplitudes = sc.linalg.lstsq(a_matrix, -self.b_vector, check_finite=True)

        self.amplitudes = amplitudes
        
        E_corr = 0.0
        for ind_nu, nu in self.dict_ind_exops.items():
            i, j, a, b = nu
            E_corr += amplitudes[ind_nu] * (2*self.ham.two_int(i, j, a, b) - self.ham.two_int(i, j, b, a))

        return E_corr