# This file is to implement the linearized CCD correction based on the paper by Boguslawski & Ayers (2015)

# Goal: create an implementation for the AP1roG wavefunction that can be generalized to other wavefunctions

### Step 1 ###
# create a basic class for the LCCD correction with the constructor __init__ 

### Step 2 ###
#  generate pool of excitation operators (for AP1roG, this is the E_ai E_bi that corresponds to the parameter t_ij^ab)
# we can store the parameters t_ij^ab as numpy arrays, similarly to how wavefunctions store the wavefunction parameters. 
# We will need a map between the index of a parameter and the corresponding exop. The CC wavefunction does something similar, where self.exops is a dictionary (keys are the excitation operator and value is the parameter index)  (see get_ind and get_exop from BaseCC in fanpy/cc/base.py, and self.exops)

### Step 3 ###
# calculate_b
# calculate the B_mu matrix elements
# for this, we have to call integrate_sd_wfn() of the passed hamiltonian. This returns the element <SD| H | wfn >. Here SD corresponds to the <\mu| excited state determinants generated by the excitation operators 

### Step 4 ###
# calculate_a
# calculate the A_mu_nu elements
# here, we should first simplify the equation (6) in the overleaf document and break it down into chunks. 

### Step 5 ## 
# solve system of linear equations
# this can be a method or something we leave up for the user. Not sure yet if it is best to let the user solve it or just do it in the class. 

### Step 6 ### 
# compute correction
# this should be what the user calls when calculating corrections. 
# It should compute the energy correction as per eq. (7) of the overleaf document


class LCCD:
    def __init__(self, wfn, ham):
        # check if wfn is AP1roG --> currently, we are only implementing the correction for this

        # save wfn and ham as properties
        # self.wfn = wfn
        # self.ham = ham

        # generate pool of double excitation operators 
        
        pass

    def generate_exops(self):
        pass
    
    def calculate_b(self):
        pass

    def calculate_a(self):
        pass

    def compute_correction(self):
        pass