# This file is to implement the linearized CCD correction based on the paper by Boguslawski & Ayers (2015)

# Goal: create an implementation for the AP1roG wavefunction that can be generalized to other wavefunctions

### Step 1 ###
# create a basic class for the LCCD correction with the constructor __init__ 

### Step 2 ###
#  generate pool of excitation operators (for AP1roG, this is the E_ai E_bi that corresponds to the parameter t_ij^ab)
# we can store the parameters t_ij^ab as numpy arrays, similarly to how wavefunctions store the wavefunction parameters. 
# We will need a map between the index of a parameter and the corresponding exop. The CC wavefunction does something similar, where self.exops is a dictionary (keys are the excitation operator and value is the parameter index)  (see get_ind and get_exop from BaseCC in fanpy/cc/base.py, and self.exops)

### Step 3 ###
# calculate_b
# calculate the B_mu matrix elements
# for this, we have to call integrate_sd_wfn() of the passed hamiltonian. This returns the element <SD| H | wfn >. Here SD corresponds to the <\mu| excited state determinants generated by the excitation operators 

### Step 4 ###
# calculate_a
# calculate the A_mu_nu elements
# here, we should first simplify the equation (6) in the overleaf document and break it down into chunks. 

### Step 5 ## 
# solve system of linear equations
# this can be a method or something we leave up for the user. Not sure yet if it is best to let the user solve it or just do it in the class. 

### Step 6 ### 
# compute correction
# this should be what the user calls when calculating corrections. 
# It should compute the energy correction as per eq. (7) of the overleaf document

import numpy as np

from fanpy.wfn.geminal.ap1rog import AP1roG
from fanpy.tools import slater

class LCCD:
    """
    Attributes:
    wfn : AP1roG
    ham : BaseHamiltonian or ??
    ref_sd : int
        Reference SD from AP1roG
    nspatial : int
    nspin : int
    exops : dict
    nparams : int
    params : np.ndarray with amplitudes

    Methods:
    __init__(self, wfn, ham)
    generate_exops(self)


    """



    def __init__(self, wfn, ham):
        # check if wfn is AP1roG --> currently, we are only implementing the correction for this

        # save wfn and ham as properties
        # self.wfn = wfn
        # self.ham = ham

        # generate pool of double excitation operators 
        
        if not isinstance(wfn, AP1roG):
            raise TypeError("Current LCCD implementation only supports AP1roG.")

        self.wfn = wfn
        self.ham = ham

        self.ref_sd = wfn.ref_sd
        self.nspatial = wfn.nspatial
        self.nspin = wfn.nspin

        self.generate_exops()
    

    def generate_exops(self):
        # Get occupied and virtual orbital indices from reference SD
        occ_indices = slater.occ_indices(self.ref_sd)
        vir_indices = slater.vir_indices(self.ref_sd, self.nspin)
        
        self.exops = {}
        param_ind = 0
        
        for i_ind, i in enumerate(occ_indices):
            for j in occ_indices[i_ind + 1:]:
                for a_ind, a in enumerate(vir_indices):
                    for b in vir_indices[a_ind + 1:]:
                        if self._is_pair_excitation(i, j, a, b):
                            continue
                        
                        # Store excitation operator: (i,j,a,b) -> parameter index
                        self.exops[(i, j, a, b)] = param_ind
                        param_ind += 1
        
        # Initialize cluster amplitude parameters
        self.nparams = len(self.exops)
        self.params = np.zeros(self.nparams)
        
    def _is_pair_excitation(self, i, j, a ,b):
        if j == i + self.nspatial and b == a + self.nspatial:
            return True
        if i == j + self.nspatial and a == b + self.nspatial:
            return True
        return False

    
    def calculate_b(self):
        pass

    def calculate_a(self):
        pass

    def compute_correction(self):
        pass