name: Other Tasks
description: "Miscellaneous tasks and issues."
labels: ["triage"]
type: "Task"
title: "Example task"

body:
- type: textarea
  attributes:
    label: "Describe the task or issue:"
  validations:
    required: true
